version: '3'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9034:9034"
#    networks:
#      - nginx_proxy_network
    restart: unless-stopped

#networks:
#  nginx_proxy_network:
#    external: true 