baseURL = "https://www.leandrosf.com"
title = "Leandro Ferreira"
theme = "PaperMod"
languageCode = "pt-br"

[params]
ShowReadingTime = true
ShowBreadCrumbs = true
comments = true
ShowCodeCopyButtons = true
homeInfoParams = { Title = "Bem-vindo ao meu site", Content = "Meu site pessoal onde compartilho projetos, ideias e conhecimentos." }

# Profile Mode
[params.profileMode]
enabled = true
title = "Leandro Ferreira"
subtitle = "Especialista SRE/DevOps | Desenvolvedor | Cloud"
imageUrl = "/pic.jpeg"
imageWidth = 300
imageHeight = 300
imageTitle = "Leandro Ferreira"

# Botões
[[params.profileMode.buttons]]
name = "Sobre"
url = "/sobre/"

[[params.profileMode.buttons]]
name = "Projetos"
url = "/projetos/"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

# Social Icons
[[params.socialIcons]]
name = "github"
url = "https://github.com/lsferreira42"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/lsferreira42/"

[[params.socialIcons]]
name = "cv"
url = "https://github.com/lsferreira42/cv"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/leandrosf.com"

[menu]

[[menu.main]]
identifier = "sobre"
name = "Sobre"
url = "/sobre/"
weight = 1

[[menu.main]]
identifier = "projetos"
name = "Projetos"
url = "/projetos/"
weight = 2

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 3

[taxonomies]
tag = "tags"
category = "categories"

[markup]

  [markup.highlight]
  style = "monokai"
